ALTER TABLE balita
ADD COLUMN status_aktif BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE bumil
ADD COLUMN status_aktif BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE busui
ADD COLUMN status_aktif BOOLEAN NOT NULL DEFAULT TRUE;