ALTER TABLE pengukuran_anak
ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 1;

ALTER TABLE pengukuran_balita
ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 1;

ALTER TABLE pengukuran_bumil
ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 1;

ALTER TABLE pengukuran_busui
ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 1;